### ISSUE TITLE
实验结果不理想

### ISSUE THREAD

**Issue by Yang-Jiahe** [vincentjzy/dictr#2]
作者您好，读了您的论文，我受益匪浅，并且非常惊叹于你们的工作。所以我尝试运行了代码，按照提供的实验步骤使用模型step_080000，并不能获得论文中所展示的旋转等图像，得到的结果与之相差甚大。但我并未对代码进行更改，只是增加将csv转换为图像的代码。我不知道是模型的问题，还是我添加的显示代码有问题，抑或是其他问题。麻烦作者能够给予完整的代码，谢谢！

**Comment by EVANGELION-Air** [comment]
请确保完整拉取仓库中的所有文件

如果你想做的是重现文章中的实验：
运行experiment.sh脚本会载入step_080000预训练模型并自动执行文章中的旋转，拉伸，Star位移场和预置裂纹软材料拉伸实验场景的位移测量，并将x/y方向的位移测量结果分别保存到对应的两个csv文件

文章中的旋转与拉伸实验测量结果的等高线图，是合位移的分布情况，因此你需要把两个csv文件进行按位矢量合成

**Comment by Yang-Jiahe** [comment]
感谢您的回复，我已经成功解决问题，再次感谢您做所做出的工作
